gazebo_ros_control/pid_gains:
    greybot_rim_front_joint:
        p: 0.01
        i: 0.01
        d: 0.0
    greybot_rim_rear_joint:
        p: 0.01
        i: 0.01
        d: 0.0
    greybot_rim_left_joint:
        p: 0.01
        i: 0.01
        d: 0.0
    greybot_rim_right_joint:
        p: 0.01
        i: 0.01
        d: 0.0